language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: OkXWga+c9hAVdT9AyUqMB4o8gtfOiba3LI5BPpvfhPPGBQIeoYiL8ULaQ5/Kt+EtJbGj1qR5M8obpEG98l29O/rVVdPTq3VE8XGNnTJRCzTbiLQ5zHRm7NBtEDUkUigP8QpJbmLUfI7Znrm3K3SiGSRLOJ0oWznI9FJsn0oQkkpa58fcjPy3KDxg5KQEJQKokiq9I9feImGIhwiEUnMDHQAAXHXf9ppqDyBEOB/dPsoZALhSlTElwyZJsh3wKuCwy9IUivTBbJ37JauiFjb5FMqVLM4CcaE6biRHZyc5i5zPlWeplxguQ78+3x51E9/fIJ4r0+Kx9CgX9y7A5r60PqZglPBd0Nz14LtkUd5wZtkztWOC6mLoW7c4fAayxQaH9RmSKzWQAhzoOECSF+sdY4fBfuUE7qmIyljGxhwqmcgifoBeRdOWgnXSKR63xacEF8TO9lXmSi2jUazmAhklTdHoue1lhHas6H/YcuSBSn6WI3VjRNI1hqPmpc7/t7SlOwCpcogQGGizU5KiQ9mbsSbYOlchIW1p8fM1RstbCZ7kZiYDLp1J+hszEZz7WFJ8f45nyJmVP0HxtHUESnkWQkSPk0Mti9v30XLGaxcEt30qNyXiCoph5zblQxwuUnIIVcPRXRqzEV5KkSN5VzX+Kh3hDmjMDyTb4w+1G2YUlg8=
  app: cryptic-caverns-89599
  on:
    repo: bmalin92/node-jwt-auth